# - name: Download Apache Kafka
#   get_url:
#     url: "https://downloads.apache.org/kafka/3.9.0/kafka_2.13-3.9.0.tgz"
#     dest: "/home/{{ user }}/kafka_2.13-3.9.0.tgz"

# - name: Create Kafka directory
#   ansible.builtin.file:
#     path: "/home/{{ user }}/kafka"
#     state: directory
  
# - name: Unzip Kafka
#   unarchive:
#     src: "/home/{{ user }}/kafka_2.13-3.9.0.tgz"
#     dest: "/home/{{ user }}/kafka/"
#     remote_src: yes

# - name: Give Kafka permissions
#   command: "chown -R {{ user }}:{{ user }} /home/{{ user }}/kafka"

# - name: Create Kafka configuration file
#   ansible.builtin.template:
#     src: kafka_config.cfg
#     dest: "/home/{{ user }}/kafka/kafka_2.13-3.9.0/config/server.properties"
#     # mode: "0755"

- name: Create running file
  ansible.builtin.template:
    src: start_server.sh
    dest: "/home/{{ user }}/start_server.sh"

- name: Give running file permissions
  command: "chmod +x /home/{{ user }}/start_server.sh"

