- name: Setup Spark consumer cluster
  hosts: vm_spark_consumer1, vm_spark_consumer2, vm_spark_consumer3, vm_spark_producer1, vm_spark_producer2, vm_spark_producer3
  become: yes
  vars:
    sudoer_name: "{{ user }}"
    setup_path: "/home/{{ user }}"
    spark_sbin_path: "/home/{{ user }}/spark/spark-3.5.3-bin-hadoop3/sbin"
    vm1_consumer_private_ip: "10.0.2.229"
    vm2_consumer_private_ip: "10.0.2.36"
    vm3_consumer_private_ip: "10.0.2.100"
    vm1_consumer_public_ip: "ec2-52-47-148-35.eu-west-3.compute.amazonaws.com"
    vm2_consumer_public_ip: "ec2-13-38-81-66.eu-west-3.compute.amazonaws.com"
    vm3_consumer_public_ip: "ec2-15-237-202-46.eu-west-3.compute.amazonaws.com"
    vm1_producer_private_ip: "10.0.3.112"
    vm2_producer_private_ip: "10.0.3.44"
    vm3_producer_private_ip: "10.0.3.109"
    vm1_producer_public_ip: "ec2-15-188-75-161.eu-west-3.compute.amazonaws.com"
    vm2_producer_public_ip: "ec2-15-188-83-112.eu-west-3.compute.amazonaws.com"
    vm3_producer_public_ip: "ec2-13-39-233-107.eu-west-3.compute.amazonaws.com"
  vars_files:
    - ../secrets.yaml
  roles:
    - ../roles/spark_generals