- name: Setup Zookeeper and Kafka
  hosts: vm_kafka1, vm_kafka2
  become: yes
  vars:
    sudoer_name: "{{ user }}"
    setup_path: "/home/{{ user }}"
    kafka_topic_name: "crypto_go"
    vm1_private_ip: "10.0.1.20"
    vm2_private_ip: "10.0.1.202"
    vm1_public_ip: "ec2-35-180-52-132.eu-west-3.compute.amazonaws.com"
    vm2_public_ip: "ec2-13-39-71-157.eu-west-3.compute.amazonaws.com"
  vars_files:
    - ../secrets.yaml
  roles:
    - ../roles/zookeeper
    - ../roles/kafka