- name: Setup Zookeeper and Kafka
  hosts: main
  become: yes
  vars:
    sudoer_name: "{{ user }}"
    setup_path: "/home/{{ user }}"
  vars_files:
    - ../secrets.yaml
  roles:
    - ../roles/zookeeper
    - ../roles/kafka