- name: Setup Spark consumer cluster
  hosts: vm_spark_consumer1, vm_spark_consumer2, vm_spark_consumer3, vm_spark_producer1, vm_spark_producer2, vm_spark_producer3
  become: yes
  vars:
    sudoer_name: "{{ user }}"
    setup_path: "/home/{{ user }}"
    spark_sbin_path: "/home/{{ user }}/spark/spark-3.5.3-bin-hadoop3/sbin"
    ssh_key_path: "/home/{{ user }}/.ssh/id_ed25519"
    vm1_consumer_private_ip: "10.0.2.241"
    vm2_consumer_private_ip: "10.0.2.77"
    vm3_consumer_private_ip: "10.0.2.127"
    vm1_consumer_public_ip: "ec2-52-47-208-192.eu-west-3.compute.amazonaws.com"
    vm2_consumer_public_ip: "ec2-51-44-82-237.eu-west-3.compute.amazonaws.com"
    vm3_consumer_public_ip: "ec2-35-180-166-216.eu-west-3.compute.amazonaws.com"
    vm1_producer_private_ip: "10.0.3.182"
    vm2_producer_private_ip: "10.0.3.252"
    vm3_producer_private_ip: "10.0.3.26"
    vm1_producer_public_ip: "ec2-13-36-174-151.eu-west-3.compute.amazonaws.com"
    vm2_producer_public_ip: "ec2-35-180-226-5.eu-west-3.compute.amazonaws.com"
    vm3_producer_public_ip: "ec2-13-38-52-147.eu-west-3.compute.amazonaws.com"
  vars_files:
    - ../secrets.yaml
  roles:
    - ../roles/spark_generals