- name: Setup Spark consumer cluster
  hosts: vm_spark_consumer1, vm_spark_consumer2, vm_spark_consumer3, vm_spark_producer1, vm_spark_producer2, vm_spark_producer3
  become: yes
  vars:
    sudoer_name: "{{ user }}"
    setup_path: "/home/{{ user }}"
    vm1_consumer_private_ip: "10.0.2.214"
    vm2_consumer_private_ip: "10.0.2.63"
    vm3_consumer_private_ip: "10.0.2.150"
    vm1_consumer_public_ip: "ec2-13-36-244-106.eu-west-3.compute.amazonaws.com"
    vm2_consumer_public_ip: "ec2-35-180-134-30.eu-west-3.compute.amazonaws.com"
    vm3_consumer_public_ip: "ec2-13-36-167-156.eu-west-3.compute.amazonaws.com"
    vm1_producer_private_ip: "10.0.3.57"
    vm2_producer_private_ip: "10.0.3.20"
    vm3_producer_private_ip: "10.0.3.240"
    vm1_producer_public_ip: "ec2-35-180-23-214.eu-west-3.compute.amazonaws.com"
    vm2_producer_public_ip: "ec2-15-188-81-19.eu-west-3.compute.amazonaws.com"
    vm3_producer_public_ip: "ec2-13-39-234-164.eu-west-3.compute.amazonaws.com"
  vars_files:
    - ../secrets.yaml
  roles:
    - ../roles/spark_generals